# Generated by Django 4.0.3 on 2022-03-28 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0002_remove_driver_id_alter_driver_user'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='driver',
        #     name='id',
        #     # field=models.AutoField(default=1, primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
