# Generated by Django 4.0.3 on 2022-03-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_id_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
