# Generated by Django 4.0.3 on 2022-04-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_remove_driver_id_alter_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='alarm_sound1',
            field=models.CharField(blank=True, choices=[('0', 'xx'), ('1', '22'), ('2', '33')], default='0', max_length=200, null=True),
        ),
    ]
