# Generated by Django 4.0.3 on 2022-03-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('hours', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, choices=[('xx2', 'xx1'), ('1', 'xx2'), ('2', 'xx3')], max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('0', 'Drowsiness'), ('1', 'Distraction')], max_length=200, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Session.session')),
            ],
        ),
    ]
