# Generated by Django 4.0.3 on 2022-03-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user',
            new_name='session_user',
        ),
    ]
