# Generated by Django 4.0.3 on 2022-03-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_rename_user_session_session_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
