# Generated by Django 4.0.3 on 2022-03-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_rename_session_user_session_user_alter_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user',
            new_name='user_session',
        ),
    ]
