# Generated by Django 4.0.3 on 2022-03-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0004_rename_user_session_user_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_session',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
