# Generated by Django 4.0.3 on 2022-04-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0005_rename_user_session_session_user_alter_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, choices=[('1', 'Drowsy'), ('2', 'Left'), ('3', 'Right'), ('4', 'Speaking')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Drowsiness'), ('1', 'Distraction_1'), ('2', 'Distraction_2')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
