# Generated by Django 4.0.3 on 2022-04-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0006_alter_log_message_alter_log_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
