# Generated by Django 4.0.3 on 2022-04-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0007_alter_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pause',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
